nodeLinker: node-modules

npmScopes:
  updater:
    npmAlwaysAuth: true
    npmAuthToken: '${GH_REGISTRY_TOKEN}'
    npmRegistryServer: 'https://npm.pkg.github.com'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.2.3.cjs

supportedArchitectures:
  os: [darwin, linux]
  cpu: [current, x64, arm64]
