---
name: CI

on:
  push:
  workflow_dispatch:
    branches: [main]

jobs:
  run-consumer-app-cypress:
    runs-on: ubuntu-latest
    # env:
    #   APP_WORKING_DIR: ''
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install # will run `yarn install` command
   
      - name: Run Cypress tests
        uses: cypress-io/github-action@v4
        with:
          config-file: apps/consumer-app/cypress.config.js
          command: |
            yarn test:ci:cypress:local \
            --tag local \
            --e2e \
            --env CYPRESS_ENV=staging
          browser: chrome
          install: false
          component: false
          spec: apps/consumer-app/cypress/e2e/errors/errors-page.spec.js
